version: "3.5"

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 3001:3000/tcp # App
      - 27017:27017/tcp # Mongo
    volumes:
      - ./vpn/client.conf:/gluetun/client.conf:ro
      - ./vpn/ca.crt:/gluetun/ca.crt
      - ./vpn/ta.key:/gluetun/ta.key
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/client.conf
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
  mongo:
    image: mongo:latest
    container_name: mongo
    network_mode: "service:gluetun"
    environment:
      - "MONGODB_URI: ${MONGODB_URI}"
      - "MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./database:/data
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  app:
    container_name: app
    network_mode: "service:gluetun"
    build: .
    depends_on:
      - mongo
    restart: unless-stopped
  
volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
