version: "3.5"

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 3001:3000/tcp
      - 27017:27017/tcp
      - 8084:8081/tcp
    volumes:
      - ./vpn/client.conf:/gluetun/client.conf:ro
      - ./vpn/ca.crt:/gluetun/ca.crt
      - ./vpn/ta.key:/gluetun/ta.key
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/client.conf
      - "OPENVPN_USER=${OPENVPN_USER}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
  app:
    container_name: app
    network_mode: "service:gluetun"
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    volumes:
      - ./admin:/usr/src/app/admin
      - ./pages:/usr/src/app/pages
      - ./lib:/usr/src/app/lib
      - ./styles:/usr/src/app/styles
  mongo:
    image: mongo:latest
    container_name: mongo
    network_mode: "service:gluetun"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
  mongo-express:
    image: mongo-express:latest
    network_mode: "service:gluetun"
    container_name: mongo-express
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: admin
       ME_CONFIG_MONGODB_SERVER: localhost
       ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongo
  
volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
